//
//  MockRepos.swift
//  AcademyChallenge
//
//  Created by Keven Esmael on 19/10/2022.
//

import Foundation

class MockRepos {
    
    var appleRepos: [Repos] = [
        Repos(id: 1, fullName: "Repos 1", unique: true),
        Repos(id: 2, fullName: "Repos 2", unique: true),
        Repos(id: 3, fullName: "Repos 3", unique: true),
        Repos(id: 4, fullName: "Repos 4", unique: true),
        Repos(id: 5, fullName: "Repos 5", unique: true),
        Repos(id: 6, fullName: "Repos 6", unique: true),
        Repos(id: 7, fullName: "Repos 7", unique: true),
        Repos(id: 8, fullName: "Repos 8", unique: true),
        Repos(id: 9, fullName: "Repos 9", unique: true),
        Repos(id: 10, fullName: "Repos 10", unique: true),
        Repos(id: 11, fullName: "Repos 11", unique: true),
        Repos(id: 12, fullName: "Repos 12", unique: true),
        Repos(id: 13, fullName: "Repos 13", unique: true),
        Repos(id: 14, fullName: "Repos 14", unique: true),
        Repos(id: 15, fullName: "Repos 15", unique: true),
        Repos(id: 16, fullName: "Repos 16", unique: true),
        Repos(id: 17, fullName: "Repos 17", unique: true),
        Repos(id: 18, fullName: "Repos 18", unique: true),
        Repos(id: 19, fullName: "Repos 19", unique: true),
        Repos(id: 20, fullName: "Repos 20", unique: true),
        Repos(id: 21, fullName: "Repos 21", unique: true),
        Repos(id: 22, fullName: "Repos 22", unique: true),
        Repos(id: 23, fullName: "Repos 23", unique: true),
        Repos(id: 24, fullName: "Repos 24", unique: true),
        Repos(id: 25, fullName: "Repos 25", unique: true),
        Repos(id: 26, fullName: "Repos 26", unique: true),
        Repos(id: 27, fullName: "Repos 27", unique: true),
        Repos(id: 28, fullName: "Repos 28", unique: true),
        Repos(id: 29, fullName: "Repos 29", unique: true),
        Repos(id: 30, fullName: "Repos 30", unique: true),
        Repos(id: 31, fullName: "Repos 31", unique: true),
        Repos(id: 32, fullName: "Repos 32", unique: true),
        Repos(id: 33, fullName: "Repos 33", unique: true),
        Repos(id: 34, fullName: "Repos 34", unique: true),
        Repos(id: 35, fullName: "Repos 35", unique: true),
        Repos(id: 36, fullName: "Repos 36", unique: true),
        Repos(id: 37, fullName: "Repos 37", unique: true),
        Repos(id: 38, fullName: "Repos 38", unique: true),
        Repos(id: 39, fullName: "Repos 39", unique: true),
        Repos(id: 40, fullName: "Repos 40", unique: true),
        Repos(id: 41, fullName: "Repos 41", unique: true),
        Repos(id: 42, fullName: "Repos 42", unique: true),
        Repos(id: 43, fullName: "Repos 43", unique: true),
        Repos(id: 44, fullName: "Repos 44", unique: true),
        Repos(id: 45, fullName: "Repos 45", unique: true),
        Repos(id: 46, fullName: "Repos 46", unique: true),
        Repos(id: 47, fullName: "Repos 47", unique: true),
        Repos(id: 48, fullName: "Repos 48", unique: true),
        Repos(id: 49, fullName: "Repos 49", unique: true),
        Repos(id: 50, fullName: "Repos 50", unique: true),
        Repos(id: 51, fullName: "Repos 51", unique: true),
        Repos(id: 52, fullName: "Repos 52", unique: true),
        Repos(id: 53, fullName: "Repos 53", unique: true),
        Repos(id: 54, fullName: "Repos 54", unique: true),
        Repos(id: 55, fullName: "Repos 55", unique: true),
        Repos(id: 56, fullName: "Repos 56", unique: true),
        Repos(id: 57, fullName: "Repos 57", unique: true),
        Repos(id: 58, fullName: "Repos 58", unique: true),
        Repos(id: 59, fullName: "Repos 59", unique: true),
        Repos(id: 60, fullName: "Repos 60", unique: true),
        Repos(id: 61, fullName: "Repos 61", unique: true),
        Repos(id: 62, fullName: "Repos 62", unique: true),
        Repos(id: 63, fullName: "Repos 63", unique: true),
        Repos(id: 64, fullName: "Repos 64", unique: true),
        Repos(id: 65, fullName: "Repos 65", unique: true),
        Repos(id: 66, fullName: "Repos 66", unique: true),
        Repos(id: 67, fullName: "Repos 67", unique: true),
        Repos(id: 68, fullName: "Repos 68", unique: true),
        Repos(id: 69, fullName: "Repos 69", unique: true),
        Repos(id: 70, fullName: "Repos 70", unique: true),
        Repos(id: 71, fullName: "Repos 71", unique: true)
    ]
}
